Ft trip history
atlp-rwanda/c4-barefoot-backend pull request #10
Opened 2021-01-05 11:03 UTC by edgar929

requester or manager can view trip history.
how to test this:
-- run (npm run dev)
-- in postman use this routes
   *localhost:3000/api/v1/trips/Nairobi/?page=0&limit=2 (to view all trips made by a given location)
   *localhost:3000/api/v1/trips (to view grouped list of all trips made by location)

2021-01-07 13:57 UTC, songa1 reviewed
I think it's fine.  All are working fine and from my view, you are ready to go. And i think about your build status, you can check your barefoot.yml file which is in GitHub/workflows

2021-01-08 07:16 UTC, Blaiseniyo approved these changes

2021-01-08 07:21 UTC, Blaiseniyo commented
I think it is good to go

2021-01-08 10:31 UTC, bdushimi requested changes

2021-01-08 10:31 UTC, bdushimi commented on src/controllers/viewTripHistory.js
> +    findTrip(res, query, location, offset, limit);
@edgar929 you don't need to pass the res object to findTrip function. FindTrip function should only get parameters/arguments that it only needs to find the trip info. FindTrip function should return the data i.e. trip info and then getTripHistory returns the response to the user. It's not a good idea to keep passing down req & res object. Kindly update elsewhere you've passed the res object down to another function.

2021-01-08 10:31 UTC, bdushimi commented on src/middlewares/sendEmail.js
> +    next(error);
@edgar929 you can pass the error object then in the errorHandler function, you can display whatever property of error.

2021-01-08 10:31 UTC, bdushimi commented on src/services/tripHistorySearch.js
> +        await db.TravelRequest.findAndCountAll({ where: query })
@edgar929 could you reduce this function complexity, lenght and improve its readability?
It has lots of .thens and ifs besides async & await aren't adequately used.

2021-01-11 07:25 UTC, bdushimi commented
@edgar929 Kindly resolve the merge conflicts

2021-01-11 09:04 UTC, merged