Ft get accommodation by Location
atlp-rwanda/c4-barefoot-backend pull request #44
Opened 2021-03-25 10:57 UTC by Blaiseniyo

# Description
This PR allows users to get accommodations in a specific location. It also allows users to get accommodation with their amenities along 

## Type of change

Please check the options that are relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How should this be manually tested or reproduced?

- pull this branch to your local repository and run seeds and migrations
- run the server
- Login 
-make a Get request to `localhost:3300/api/v1/accommodations/location/23fd8031-52d6-4150-958c-c162ba9e8f5c?page=1` (to get accommodation in a location with that Id)

-Make a Get request to `localhost:3300/api/v1/accommodations/7a7ce9e2-ce8a-4d76-9626-cfabf2009e42` (to all the amenities for an accommodation with Id)

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

# Screenshots (if applicable)

2021-03-27 20:58 UTC, Noel2002 requested changes
![ERR2](https://user-images.githubusercontent.com/64746276/112734440-659de600-8f4e-11eb-95d3-46d4d265cace.JPG)
I am getting this error when I try to get accommodations by location on the higher page which is not supposed to have any accommodation.
For example, there is a location that has one accommodation associated to it. Since getting accommodations by location returns a paginated list, when I try to get the first page of accommodations' list, I get that one accommodation that is associated to the location. However, the issue rise when I try to get the second page of the list, instead of getting, maybe, an empty array, I get this error.
I think that you may need to look into that.

2021-03-28 17:31 UTC, Noel2002 submitted a review, later dismissed

2021-03-31 17:27 UTC, edgar929 reviewed
this feature is working fine, I used it .

2021-03-31 17:31 UTC, edgar929 approved these changes

2021-03-31 17:43 UTC, Noel2002 approved these changes

2021-03-31 18:03 UTC, merged